name: パックを出力しArtifactsにアップロード

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: パックを生成
      id: gen-pack
      run: |
        echo "pack_file_name=$(basename $(./gen-pack.sh))" >> $GITHUB_OUTPUT
      shell: bash

    - name: Artifactsにアップロード
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.gen-pack.outputs.pack_file_name }}
        path: pack/${{ steps.gen-pack.outputs.pack_file_name }}
